### ISSUE TITLE
考虑在文档中使用Version Catalogs作为库导入方式

### ISSUE THREAD

**Issue by ryuunoakaihitomi** [FlyJingFish/AndroidAOP#65]
## 理由

AndroidAOP包含插件和导入的库。按照现在的文档，改版本号需要修改两处地方，不是很方便。
使用[Version Catalogs](https://docs.gradle.org/current/userguide/version_catalogs.html) 可以只需要更改一次版本号，方便统一管理依赖。

而且此功能在Gradle [7.0](https://docs.gradle.org/7.0/release-notes.html) 中实验性导入并于 [7.4](https://docs.gradle.org/7.4/release-notes.html) 中稳定。和AndroidAOP的适用Gradle版本(7.6+)完美契合。

## 使用示例

* 在`/gradle/libs.versions.toml`中添加以下配置：
```toml

[versions]
#...
androidaop = '2.6.5'

[libraries]
#...
androidaop-core = { module = "io.github.FlyJingFish.AndroidAop:android-aop-core", version.ref = "androidaop" }
androidaop-extra = { module = "io.github.FlyJingFish.AndroidAop:android-aop-extra", version.ref = "androidaop" }
androidaop-processor = { module = "io.github.FlyJingFish.AndroidAop:android-aop-processor", version.ref = "androidaop" }

[plugins]
#...
androidaop = { id = "io.github.FlyJingFish.AndroidAop.android-aop", version.ref = "androidaop" }
androidaop-moduleref = { id = "android.aop" }
```

* 在项目根目录的`build.gradle`中添加：
```groovy
plugins {
    alias(libs.plugins.androidaop) apply false
    //...
}
```

* 在app（或者其他子模块）的`build.gradle`中添加：
```groovy

plugins {
    //...
    alias(libs.plugins.androidaop.moduleref)
}

dependencies {
    //...
    implementation libs.androidaop.core
    implementation libs.androidaop.extra
    annotationProcessor libs.androidaop.processor
    //...
}
```

实测可以成功导入。
